/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FrmPendaftaran.java
 *
 * Created on Sep 6, 2013, 6:51:58 AM
 */
package rumahsakit.Gui;

import ca.odell.glazedlists.GlazedLists;
import ca.odell.glazedlists.swing.AutoCompleteSupport;
import com.mysql.jdbc.Connection;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JOptionPane;
import rumahsakit.Entity.Pendaftaran;
import rumahsakit.Service.DokterService;
import rumahsakit.Service.JaminanService;
import rumahsakit.Service.PasienService;
import rumahsakit.Service.PendaftaranService;
import rumahsakit.Service.SpesialisService;
import rumahsakit.TabelModel.TabelModelDokter;
import rumahsakit.TabelModel.TabelModelJaminan;
import rumahsakit.TabelModel.TabelModelSpesialis;

/**
 *
 * @author asus
 */
public class FrmPendaftaran extends javax.swing.JInternalFrame {

    PendaftaranService pds = new PendaftaranService();
    PasienService pss = new PasienService(); // OK
    DokterService ds = new DokterService();
    TabelModelDokter tabelModelDokter = new TabelModelDokter();
    JaminanService js = new JaminanService();
    TabelModelJaminan tabelModelJaminan = new TabelModelJaminan();
    SpesialisService ss = new SpesialisService(); // OK
    TabelModelSpesialis tabelModelSpesialis = new TabelModelSpesialis();
    Connection connection;
    AutoCompleteSupport completeSpesialis, completeDokter, completeJaminan = null;

    /** Creates new form FrmPendaftaran */
    public FrmPendaftaran() {
        initComponents();

        /*Mengisi data SPESIALIS di JComboBox dengan auto-complete*/
        tabelModelSpesialis.setData(ss.serviceGetAllSpesialis());
        int spesialis = tabelModelSpesialis.getRowCount();
        completeSpesialis = AutoCompleteSupport.install(
                cmbSpesialis, GlazedLists.eventListOf(ss.serviceGetNamaSpesialis(spesialis)));

        cmbSpesialis.addItemListener(new ItemListener() {

            public void itemStateChanged(ItemEvent e) {
                try {
                    /*Me-remove All item dengan setModel*/
                    String[] list = new String[]{""};
                    cmbNmDokter.setModel(new javax.swing.DefaultComboBoxModel(list));

                    /*Mengambil data pilihan spesialis*/
                    String nama = (String) cmbSpesialis.getSelectedItem();
                    String kodeSpesialis = ss.serviceGetIDSpesialis(nama);
                    //System.out.println("Kode spesialis = "+kodeSpesialis);

                    /*Mengisi pilihan nama dokter berdasarkan pilihan spesialis*/
                    tabelModelDokter.setData(ds.serviceGetByIdSpesialis(kodeSpesialis));
                    int b = tabelModelDokter.getRowCount();
                    completeDokter = AutoCompleteSupport.install(
                            cmbNmDokter, GlazedLists.eventListOf(ds.serviceNamaDokter(kodeSpesialis, b)));
                } catch (Throwable t) {
                }
            }
        });

        /*Mengisi data JAMINAN di JComboBox dengan auto-complete*/
        tabelModelJaminan.setData(js.serviceGetAllJaminan());
        int jaminan = tabelModelJaminan.getRowCount();
        completeJaminan = AutoCompleteSupport.install(
                cmbJaminan, GlazedLists.eventListOf(js.serviceTampilNamaJaminan(jaminan)));

    }

    public void clear(){
        txtIdPasien.setText("");
        txtNmPasien.setText("");
        cmbSpesialis.setSelectedItem("");
        cmbJaminan.setSelectedItem("");
        txtIdPasien.requestFocus();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtNmPasien = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtIdPasien = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        cmbSpesialis = new javax.swing.JComboBox();
        cmbNmDokter = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        cmbJaminan = new javax.swing.JComboBox();
        btnBatal = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();

        setClosable(true);
        setTitle("Pendaftaran Pasien");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Data Pasien"));

        jLabel2.setText("Nama Pasien");

        txtNmPasien.setEditable(false);
        txtNmPasien.setFocusable(false);

        jLabel1.setText("ID Pasien");

        txtIdPasien.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtIdPasienKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtIdPasien, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtNmPasien, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdPasien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNmPasien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Data Dokter"));

        jLabel3.setText("Spesialis");

        cmbSpesialis.setEditable(true);

        cmbNmDokter.setEditable(true);

        jLabel4.setText("Nama Dokter");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(cmbSpesialis, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbNmDokter, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbSpesialis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbNmDokter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Data Jaminan"));

        cmbJaminan.setEditable(true);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cmbJaminan, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(280, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cmbJaminan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnBatal.setText("BATAL");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });

        btnSimpan.setText("SIMPAN");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(333, Short.MAX_VALUE)
                .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBatal, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                    .addComponent(btnSimpan, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdPasienKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdPasienKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            //JOptionPane.showMessageDialog(rootPane, "Haii");
            String nama = pss.serviceNamaByIdPasien(txtIdPasien.getText());
            txtNmPasien.setText(nama);
        }
    }//GEN-LAST:event_txtIdPasienKeyPressed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnBatalActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:

        SimpleDateFormat sdf = new SimpleDateFormat("ddMMyyyy");
        Calendar cal = Calendar.getInstance();
        String tgl = sdf.format(cal.getTime());
        //String tgl = "04092013";

        String nomor = pds.generateNomorService(tgl);

        String hasilPasien = pss.serviceNamaByIdPasien(txtIdPasien.getText());

        String pilihDokter = (String) cmbNmDokter.getSelectedItem();
        String pilihJaminan = (String) cmbJaminan.getSelectedItem();

        String idDokter = ds.serviceTampilIdDokterByNama((pilihDokter));
        String idJaminan = js.getIdJaminanByNama(pilihJaminan);
        
        if (hasilPasien == null) {
            JOptionPane.showMessageDialog(rootPane, "Periksa kembali ID Pasien!","Validasi",JOptionPane.WARNING_MESSAGE);
        } else if ((pilihDokter == null) || (pilihDokter.equalsIgnoreCase("")) || (pilihDokter.equalsIgnoreCase(" "))) {
            JOptionPane.showMessageDialog(rootPane, "Dokter Tidak Boleh Kosong!","Validasi",JOptionPane.WARNING_MESSAGE);
        } else if (idDokter == null) {
            JOptionPane.showMessageDialog(rootPane, "Periksa kembali nama dokter!","Validasi",JOptionPane.WARNING_MESSAGE);
        } else if ((pilihJaminan == null) || (pilihJaminan.equalsIgnoreCase("")) || (pilihJaminan.equalsIgnoreCase(" "))) {
            JOptionPane.showMessageDialog(rootPane, "Jaminan Tidak Boleh Kosong!","Validasi",JOptionPane.WARNING_MESSAGE);
        } else if (idJaminan == null) {
            JOptionPane.showMessageDialog(rootPane, "Periksa kembali nama jaminan!","Validasi",JOptionPane.WARNING_MESSAGE);
        } else {
            //System.out.println(pds.generateNomorService(tgl));

            Pendaftaran p = new Pendaftaran();
            p.setNoReg(nomor);
            p.setIdPasien(txtIdPasien.getText());
            p.setIdDokter(idDokter);
            p.setIdJaminan(idJaminan);
            pds.insertPendaftaranService(p);
            clear();
//            JOptionPane.showMessageDialog(rootPane, "No Daftar  : " + nomor+"\n"
//                    + "ID Pasien  : " + txtIdPasien.getText()+"\n"
//                    +"ID Dokter  : " + idDokter+"\n"
//                    +"ID Jaminan : " + idJaminan);

//            System.out.println("No Daftar  : " + nomor);
//            System.out.println("ID Pasien  : " + txtIdPasien.getText());
//            System.out.println("ID Dokter  : " + idDokter);
//            System.out.println("ID Jaminan : " + idJaminan);
        }
    }//GEN-LAST:event_btnSimpanActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JComboBox cmbJaminan;
    private javax.swing.JComboBox cmbNmDokter;
    private javax.swing.JComboBox cmbSpesialis;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField txtIdPasien;
    private javax.swing.JTextField txtNmPasien;
    // End of variables declaration//GEN-END:variables
}
